# -*- coding: utf-8 -*-
"""Bell states.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sDShf1ajj8Qa8CjuSnP37hroxIZhOTCS

# Qiskit Installation with required Modules
"""

!pip install qiskit
!pip install qiskit-aer
!pip install matplotlib
!pip install pylatexenc

"""# Import Block"""

from qiskit import QuantumCircuit
from qiskit_aer import Aer, AerSimulator # Added AerSimulator
from qiskit.visualization import plot_histogram
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_bloch_multivector
import matplotlib.pyplot as plt

"""# Pauli X gate on Q-bit State $|0>$"""

# Create a 1-qubit quantum circuit
qc = QuantumCircuit(1)

# Apply X gate to the qubit
qc.y(0)

# Get the final statevector
state = Statevector.from_instruction(qc)

# Show the circuit
print("Circuit with X gate:")
display(qc.draw('mpl'))

# Print the statevector
print("Statevector after applying X gate:")
print(state)

# Show Bloch sphere
display(plot_bloch_multivector(state))

"""# Pauli X gate on state $|1>$"""

# Create a 1-qubit quantum circuit
qc = QuantumCircuit(1)

# Initialize input state to |1>
qc.x(0)   # <-- prepares |1⟩ as the input

# Apply X gate to the qubit (on |1>)
qc.z(0)

# Get the final statevector
state = Statevector.from_instruction(qc)

# Show the circuit
print("Circuit with input |1> and then X gate applied:")
display(qc.draw('mpl'))

# Print the statevector
print("Statevector after applying X on |1> input:")
print(state)

# Show Bloch sphere
display(plot_bloch_multivector(state))

"""# Circuit for Hadamard Gate:

# q: ───H───

"""

# 1 quibit system
qc = QuantumCircuit(1)
# applying hadamard gate
qc.h(0)

# Get the final statevector
state = Statevector.from_instruction(qc)

# Show the circuit
print("Circuit with Hadamard gate:")
display(qc.draw('mpl'))

# Print the statevector
print("Statevector after applying hadamard gate:")
print(state)

# Show Bloch sphere
display(plot_bloch_multivector(state))

"""# Two qubit Circuit with CNOT Gate:

Control-qubit $|1>$

Target-qubit $|0>$
"""

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector

# Create a 2-qubit circuit
qc = QuantumCircuit(2)

# Initialize the state, for example |10> (control=1, target=0)
qc.x(0)   # put qubit-0 in state |1>
qc.barrier()

# Apply CNOT: control=0, target=1
qc.cx(0, 1)

# Get the statevector
state = Statevector.from_instruction(qc)

print("Statevector after applying CNOT (control=0, target=1):")
print(state)

print("Circuit with control |0>, target |1>, then CNOT:")
display(qc.draw('mpl'))

"""# Two qubit Circuit with CNOT Gate:

Control-qubit $|0>$

Target-qubit $|1>$
"""

# Create 2-qubit quantum circuit
qc = QuantumCircuit(2)

# Prepare input state |0>|1>
qc.x(1)   # target qubit = |1>, control stays |0>

# Apply CNOT (control=0, target=1)
qc.cx(0, 1)

# Get final statevector
state = Statevector.from_instruction(qc)

# Show circuit
print("Circuit with control |0>, target |1>, then CNOT:")
display(qc.draw('mpl'))

# Show statevector
print("\nStatevector after applying CNOT:")
print(state)

# Bloch sphere visualization (both qubits)
display(plot_bloch_multivector(state))

"""# Two qubit Circuit with CNOT Gate:

 control-qubit in state $|1>$

 Target-qubit in state $|0>$
"""

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_bloch_multivector
import matplotlib.pyplot as plt

# Create 2-qubit quantum circuit
qc = QuantumCircuit(2)

# Prepare input state: control (q1) = |1>, target (q0) = |0>
qc.x(0)   # put qubit-1 into |1>

# Apply CNOT: control = qubit-1, target = qubit-0
qc.cx(0, 1)

# Get final statevector
state = Statevector.from_instruction(qc)

# Show circuit
print("Circuit with control qubit=q0, target qubit=q1 (CNOT):")
display(qc.draw('mpl'))

# Show statevector
print("\nStatevector after applying CNOT:")
print(state)

# Bloch sphere visualization (both qubits)
display(plot_bloch_multivector(state))

"""# **Bell's  State Generation**

Bell states are the four maximally entangled two-qubit states. They have perfect correlations (or anti-correlations), cannot be factored, and form the Bell basis. They are the simplest playground for studying entanglement, nonlocality, and quantum communication.

Following are the four bell state;

$$
|\Phi^+\rangle = \frac{1}{\sqrt{2}} \big( |00\rangle + |11\rangle \big)
$$

$$
|\Phi^-\rangle = \frac{1}{\sqrt{2}} \big( |00\rangle - |11\rangle \big)
$$

$$
|\Psi^+\rangle = \frac{1}{\sqrt{2}} \big( |01\rangle + |10\rangle \big)
$$

$$
|\Psi^-\rangle = \frac{1}{\sqrt{2}} \big( |01\rangle - |10\rangle \big)
$$

# 1. Code to built Quantum Circuit Diagram for Bell State:

 $$
|\Phi^+\rangle = \frac{1}{\sqrt{2}} \big( |00\rangle + |11\rangle \big)
$$
"""

# 2 qubit Circuit wit Hadamard and CNOT gate to get bell states
qc = QuantumCircuit(2, 2) # Added a second argument to create classical bits for measurement
qc.h(0)
qc.cx(0, 1)

# Show circuit (before measurement for statevector calculation)
print("Circuit with control state |0>, target |0>, then applying Hadamard and CNOT:")
display(qc.draw('mpl'))

# Get the final statevector (before measurement)
state = Statevector.from_instruction(qc)

# Show statevector
print("\nStatevector of Bell State:")
print(state)

# Bloch sphere visualization (both qubits)
display(plot_bloch_multivector(state))

# Apply measurement for simulation
qc.measure([0,1], [0,1])

# Run the circuit on a simulator and plot histogram
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)  # Run 1024 times to get counts
result = job.result()
counts = result.get_counts(qc)
print("\nMeasurement outcomes histogram:")
display(plot_histogram(counts)) # Wrapped in display()

from qiskit_aer import AerSimulator

# Run the circuit on a simulator
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)  # Run 1024 times to get counts
result = job.result()
counts = result.get_counts(qc)

# Plot the histogram of the measurement results
plot_histogram(counts)

"""# 2. Code to built Quantum Circuit Diagram for Bell State:


$$
|\Psi^+\rangle = \frac{1}{\sqrt{2}} \big( |01\rangle + |10\rangle \big)
$$
"""

# 2 qubit Circuit wit Hadamard and CNOT gate to get bell states
qc = QuantumCircuit(2, 2) # Changed to include classical bits
qc.h(0)
qc.x(1)
qc.cx(0, 1)

# Show circuit (before measurement for statevector calculation)
print("Circuit with control state |0>, target |1>, then applying Hadamard and CNOT:")
display(qc.draw('mpl'))

# Get the final statevector (before measurement)
state = Statevector.from_instruction(qc)

# Show statevector
print("\nStatevector of Bell State:")
print(state)

# Bloch sphere visualization (both qubits)
display(plot_bloch_multivector(state))

# Apply measurement for simulation
qc.measure([0,1], [0,1]) # Added measurement

# Run the circuit on a simulator and plot histogram
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)
result = job.result()
counts = result.get_counts(qc)
print("\nMeasurement outcomes histogram:")
display(plot_histogram(counts)) # Wrapped in display()

"""# 3. Code to built Quantum Circuit Diagram for Bells state:

$$
|\Phi^-\rangle = \frac{1}{\sqrt{2}} \big( |00\rangle - |11\rangle \big)
$$
"""

# 2 qubit Circuit wit Hadamard and CNOT gate to get bell states
qc = QuantumCircuit(2, 2) # Changed to include classical bits
qc.x(0)
qc.h(0)
qc.cx(0, 1)

# Show circuit (before measurement for statevector calculation)
print("Circuit with control state |0>, target |1>, then applying Hadamard and CNOT:")
display(qc.draw('mpl'))

# Get the final statevector (before measurement)
state = Statevector.from_instruction(qc)

# Show statevector
print("\nStatevector of Bell State:")
print(state)

# Bloch sphere visualization (both qubits)
display(plot_bloch_multivector(state))

# Apply measurement for simulation
qc.measure([0,1], [0,1]) # Added measurement

# Run the circuit on a simulator and plot histogram
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)
result = job.result()
counts = result.get_counts(qc)
print("\nMeasurement outcomes histogram:")
display(plot_histogram(counts)) # Wrapped in display()

"""# 4. Code to built quantum circuit diagram for bells state:

$$
|\Psi^-\rangle = \frac{1}{\sqrt{2}} \big( |01\rangle - |10\rangle \big)
$$
"""

# 2 qubit Circuit wit Hadamard and CNOT gate to get bell states
qc = QuantumCircuit(2, 2) # Changed to include classical bits
qc.x(0)
qc.x(1)
qc.h(0)
qc.cx(0, 1)

# Show circuit (before measurement for statevector calculation)
print("Circuit with control state |0>, target |1>, then applying Hadamard and CNOT:")
display(qc.draw('mpl'))

# Get the final statevector (before measurement)
state = Statevector.from_instruction(qc)

# Show statevector
print("\nStatevector of Bell State:")
print(state)

# Bloch sphere visualization (both qubits)
display(plot_bloch_multivector(state))

# Apply measurement for simulation
qc.measure([0,1], [0,1]) # Added measurement

# Run the circuit on a simulator and plot histogram
simulator = AerSimulator()
job = simulator.run(qc, shots=1024)
result = job.result()
counts = result.get_counts(qc)
print("\nMeasurement outcomes histogram:")
display(plot_histogram(counts)) # Wrapped in display()

